### ISSUE TITLE
download-raw-data.py doesn't work in IE11

### ISSUE THREAD

**Issue by amarvin** [plotly/dash-recipes#11]
URI links aren't allowed in IE11, so the download CSV links don't work.  Is there an alternative that is easy to implement with Dash? Maybe some of the answers from [this stackoverflow question](https://stackoverflow.com/q/3916191/6068036)  would help, like using another JavaScript library like downloadify.js or download.js.

**Comment by chriddyp** [comment]
Hm, interesting. Let's keep this thread in the community forum (all of these examples were created in response to community forum questions). In particular, this thread? https://community.plot.ly/t/download-raw-data/4700

That thread has some other alternatives with `/static/data.csv` urls

**Comment by chriddyp** [comment]
This is the other approach for downloading raw data: https://community.plot.ly/t/allowing-users-to-download-csv-on-click/5550/4

**Comment by chriddyp** [comment]
And maybe we should add a comment to the `download-raw-data.py` example

**Comment by chriddyp** [comment]
> ike using another JavaScript library like downloadify.js or download.js.

And this looks like it could be a good canditate for a dash component, I made an issue here: https://github.com/plotly/dash-core-components/issues/216
