### ISSUE TITLE
Separate callbacks into own file

### ISSUE THREAD

**Issue by brylie** [plotly/dash-recipes#19]
The Dash guide shows how to create a Dash app in a single file. However, the app file quickly grows to several hundred files for a moderately sized dashboard. The question of how to organize Dash apps, so that callbacks are in a separate file, has been raised several times in the Dash community forum without help. Please add a recipe for how to break down a Dash app into separate files, as can be seen in the Dash [slapdash boilerplate](https://github.com/ned2/slapdash/tree/master/src/slapdash). The Slapdash project is well-designed, but leaves a lot to be desired in terms of explaining **why** the files are structured in such a way and **how** to create a simple Dash project with that file structure.

**Comment by brylie** [comment]
Related issue in Slapdash project:
https://github.com/ned2/slapdash/issues/6

Related discussions in community forum:
https://community.plot.ly/t/dash-callback-in-a-separate-file/14122
https://community.plot.ly/t/callbacks-in-a-separate-file/15034

**Comment by chriddyp** [comment]
A better place for this issue would be in the `dash-docs` repo: https://github.com/plotly/dash-docs/issues/. In Dash Docs, we have a tutorial on this in https://dash.plot.ly/urls and I'd accept a PR to make that more discoverable
