### ISSUE TITLE
BUG: dash-error-message-display

### ISSUE THREAD

**Issue by c-thiel** [plotly/dash-recipes#2]
First of all, thank you for this great collection. It really helped me alot.

I was just trying to get some pop-up messages to work with dash. I tried the `dash-display-error-message.py` script, however couldn't get it to work. 
In the Browser window I see the notice `adding window.onerror`, however the function doesn't get triggered on error. Status 500 is triggered by entering error in the input field `"POST /_dash-update-component HTTP/1.1" 500` .

As I am no HTML-expert, any help would be appreciated.

Thanks!

**Comment by chriddyp** [comment]
Hm, I don't quite remember the context of `dash-display-error-message.py`, but it's probably not what you're looking for. It looks pretty idiosyncratic/specific to me. 

The examples in this repo are created directly from answering specific user questions / exploring different concepts, so they're not all useful by themselves. I recommend asking specific questions in the Dash community forum: https://community.plot.ly/c/dash/
