### ISSUE TITLE
multi-page-app not responding

### ISSUE THREAD

**Issue by MokeEire** [plotly/dash-recipes#20]
The app contained within [multi-page-app](https://github.com/plotly/dash-recipes/tree/master/multi-page-app) is not producing anything when run through a terminal in JupyterLab.

I have the same file structure:
- app.py
- index.py
- apps
    - \_\_init\_\_.py
    - app1.py
    - app2.py

And run the command:

`python app.py`

And nothing is produced.  Is there something being used in this code that has since been deprecated?

**Comment by vargasvic** [comment]
The same issue with me, the app is throwing this error when trying to run: 
AttributeError: ('Invalid config key. Some settings are only available via the Dash constructor', 'supress_callback_exceptions')

**Comment by chriddyp** [comment]
Please view the official documentation instead, this repo isn't really maintained, it's just a collection of various scripts and things I used to help folks out on the community forum: http://dash.plotly.com/urls
