### ISSUE TITLE
Multiple intervals problem

### ISSUE THREAD

**Issue by JPabloVasquez** [plotly/dash-recipes#6]
Hi, im trying to execute the example "multiple-intervals.py" to see how it works and it gets me this error : "ValueError: cannot have a multithreaded and multi process server" , i dont understand why, thank you

**Comment by chriddyp** [comment]
It's an issue with the latest version of flask. Just set `threaded=False` in `app.run_server` _or_ keep `threaded=True` but set `processes=1`
